// Copyright © Erickson Lopez. MIT License.
using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace EricksonLopez.Specification.Generators;

/// <summary>
/// Generates strongly-typed ordering helpers and AOT-safe specification metadata
/// for types annotated with <c>[Spec]</c>.
/// </summary>
/// <remarks>
/// <para>
/// This generator processes classes annotated with the <c>[Spec]</c> attribute and
/// emits strongly-typed ordering extensions to avoid string-based ordering APIs.
/// </para>
/// <para>
/// Example:
/// <code>
/// [Spec]
/// public sealed partial class CustomerSpecifications
/// {
///     // Generator produces:
///     //   public static Expression&lt;Func&lt;Customer, object?&gt;&gt; OrderByName
///     //   public static Expression&lt;Func&lt;Customer, object?&gt;&gt; OrderByCreditLimit
///     //   ... etc
/// }
/// </code>
/// </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class SpecificationGenerator : IIncrementalGenerator
{
    internal static readonly DiagnosticDescriptor RequiresPartialDescriptor = new DiagnosticDescriptor(
        "SPEC100",
        "Specification class must be partial",
        "'{0}' is decorated with [Spec] but is not declared as partial. Add the 'partial' keyword.",
        "Specification",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register attributes for injection
        context.RegisterPostInitializationOutput(RegisterSpecAttributes);

        // Pipeline: find all classes marked [Spec]
        // Stryker disable Linq,Logical : Roslyn incremental generator pipeline target symbol and attribute non-null guarantee
        var specClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "EricksonLopez.Specification.SpecAttribute",
                predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
                transform: static (ctx, _) => (Target: (INamedTypeSymbol)ctx.TargetSymbol, Attribute: ctx.Attributes[0]))
            .Where(static item => item.Target is not null);

        // Pipeline: find all classes marked [SpecColumnResolver]
        var resolverClasses = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "EricksonLopez.Specification.SpecColumnResolverAttribute",
                predicate: static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
                transform: static (ctx, _) => (Target: (INamedTypeSymbol)ctx.TargetSymbol, Attribute: ctx.Attributes[0]))
            .Where(static item => item.Target is not null);
        // Stryker restore Linq,Logical

        // Generate code for [Spec] classes
        context.RegisterSourceOutput(specClasses, GenerateSpecificationCode!);

        // Generate code for [SpecColumnResolver] classes
        context.RegisterSourceOutput(resolverClasses, GenerateColumnResolverCode!);
    }

    private static void RegisterSpecAttributes(IncrementalGeneratorPostInitializationContext context)
    {
        var specAttrCode = """
            // <auto-generated/>
            namespace EricksonLopez.Specification
            {
                /// <summary>
                /// Marks a class for specification source generation.
                /// The generator will emit strongly-typed ordering helpers.
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                public sealed class SpecAttribute : global::System.Attribute
                {
                    /// <summary>Gets the entity type.</summary>
                    public global::System.Type? EntityType { get; }

                    /// <summary>Initializes a new instance of the attribute.</summary>
                    public SpecAttribute(global::System.Type? entityType = null) => EntityType = entityType;
                }
            }
            """;
        context.AddSource("SpecAttribute.g.cs", SourceText.From(specAttrCode, Encoding.UTF8, SourceHashAlgorithm.Sha1));

        var colResolverAttrCode = """
            // <auto-generated/>
            namespace EricksonLopez.Specification
            {
                /// <summary>
                /// Specifies the naming convention for SQL column names.
                /// </summary>
                public enum NamingConvention
                {
                    /// <summary>Snake case (e.g., total_purchases).</summary>
                    SnakeCase = 0,
                    /// <summary>Pascal case (e.g., TotalPurchases).</summary>
                    PascalCase = 1,
                    /// <summary>Camel case (e.g., totalPurchases).</summary>
                    CamelCase = 2,
                    /// <summary>Exact property name match.</summary>
                    Exact = 3
                }

                /// <summary>
                /// Generates a compile-time zero-reflection IColumnNameResolver implementation.
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                public sealed class SpecColumnResolverAttribute : global::System.Attribute
                {
                    /// <summary>Gets the entity type.</summary>
                    public global::System.Type EntityType { get; }

                    /// <summary>Gets or sets the column naming convention.</summary>
                    public NamingConvention Convention { get; set; } = NamingConvention.SnakeCase;

                    /// <summary>Initializes a new instance of the attribute.</summary>
                    public SpecColumnResolverAttribute(global::System.Type entityType) => EntityType = entityType;
                }
            }
            """;
        context.AddSource("SpecColumnResolverAttribute.g.cs", SourceText.From(colResolverAttrCode, Encoding.UTF8, SourceHashAlgorithm.Sha1));
    }

    private static void GenerateSpecificationCode(
        SourceProductionContext context,
        (INamedTypeSymbol Target, AttributeData Attribute) item)
    {
        var symbol = item.Target;
        if (!symbol.IsPartial())
        {
            context.ReportDiagnostic(Diagnostic.Create(
                RequiresPartialDescriptor,
                symbol.Locations[0],
                symbol.Name));
            return;
        }

        INamedTypeSymbol? entityTypeSymbol = null;
        var attribute = item.Attribute;
        // Stryker disable Equality,Logical : Roslyn attribute constructor argument count check
        if (attribute.ConstructorArguments.Length > 0)
        {
            entityTypeSymbol = attribute.ConstructorArguments[0].Value as INamedTypeSymbol;
        }
        // Stryker restore Equality,Logical

        if (entityTypeSymbol is null)
        {
            var baseType = symbol.BaseType;
            while (baseType is not null)
            {
                if (baseType.Name == "Specification" && baseType.TypeArguments.Length == 1 && baseType.TypeArguments[0] is INamedTypeSymbol entityType)
                {
                    entityTypeSymbol = entityType;
                    // Stryker disable once Statement,Block : Early loop break optimization
                    break;
                }
                baseType = baseType.BaseType;
            }
        }

        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : $"namespace {symbol.ContainingNamespace};";

        var helpersBuilder = new System.Text.StringBuilder();
        if (entityTypeSymbol is not null)
        {
            var entityFullName = entityTypeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var properties = entityTypeSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
                .ToList();

            foreach (var prop in properties)
            {
                helpersBuilder.Append($"    public static readonly global::System.Linq.Expressions.Expression<global::System.Func<{entityFullName}, object?>> OrderBy{prop.Name} = x => (object?)x.{prop.Name};\n");
            }
        }

        var bodyContent = helpersBuilder.Length > 0
            ? helpersBuilder.ToString().TrimEnd()
            : "    // Strongly-typed ordering helpers generated by EricksonLopez.Specification.Generators\n    // Add properties to your entity class and they will appear here as ordering expressions.";

        var source = $$"""
            // <auto-generated/>
            {{ns}}

            partial class {{symbol.Name}}
            {
            {{bodyContent}}
            }
            """;

        context.AddSource($"{symbol.Name}.g.cs", SourceText.From(source, Encoding.UTF8, SourceHashAlgorithm.Sha1));
    }

    private static void GenerateColumnResolverCode(
        SourceProductionContext context,
        (INamedTypeSymbol Target, AttributeData Attribute) item)
    {
        var symbol = item.Target;
        if (!symbol.IsPartial())
        {
            context.ReportDiagnostic(Diagnostic.Create(
                RequiresPartialDescriptor,
                symbol.Locations[0],
                symbol.Name));
            return;
        }

        var entityTypeSymbol = item.Attribute.ConstructorArguments[0].Value as INamedTypeSymbol;
        if (entityTypeSymbol is null)
            return;

        var conventionValue = (int)(item.Attribute.NamedArguments.FirstOrDefault(a => a.Key == "Convention").Value.Value ?? 0);

        var properties = entityTypeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
            .ToList();

        var switchArms = new System.Text.StringBuilder();
        foreach (var prop in properties)
        {
            var propName = prop.Name;
            var colName = ConvertName(propName, conventionValue);
            switchArms.Append($"        \"{propName}\" => \"{colName}\",\n");
        }
        switchArms.Append($"        _ => throw new global::System.ArgumentException($\"Unknown property '{{propertyName}}' for entity '{entityTypeSymbol.Name}'.\", nameof(propertyName))");

        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : $"namespace {symbol.ContainingNamespace};";

        var isStatic = symbol.IsStatic;
        var declaration = isStatic
            ? $"partial class {symbol.Name}"
            : $"partial class {symbol.Name} : global::EricksonLopez.Specification.Sql.IColumnNameResolver";

        var instanceProperty = isStatic
            ? string.Empty
            : $"\n    public static readonly {symbol.Name} Instance = new();\n";

        var methodModifiers = isStatic ? "public static string" : "public string";

        var source = $$"""
            // <auto-generated/>
            #nullable enable
            {{ns}}

            {{declaration}}
            {{{instanceProperty}}
                {{methodModifiers}} Resolve(string propertyName) => propertyName switch
                {
            {{switchArms}}
                };
            }
            """;

        context.AddSource($"{symbol.Name}.g.cs", SourceText.From(source, Encoding.UTF8, SourceHashAlgorithm.Sha1));
    }

    private static string ConvertName(string propertyName, int convention)
    {
        return convention switch
        {
            1 => propertyName, // PascalCase
            2 => char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1), // CamelCase
            3 => propertyName, // Exact
            _ => ToSnakeCase(propertyName) // SnakeCase
        };
    }

    private static string ToSnakeCase(string text)
    {
        if (string.IsNullOrEmpty(text)) return text;
        var sb = new System.Text.StringBuilder(text.Length + 5);
        for (var i = 0; i < text.Length; i++)
        {
            var c = text[i];
            if (char.IsUpper(c))
            {
                if (i > 0 && text[i - 1] != '_')
                    sb.Append('_');
                sb.Append(char.ToLowerInvariant(c));
            }
            else
            {
                sb.Append(c);
            }
        }
        return sb.ToString();
    }
}



