// Copyright © Erickson Lopez. MIT License.
using System;
using System.Threading;
using System.Threading.Tasks;
using AwesomeAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Testing.Verifiers;
using Xunit;

namespace EricksonLopez.Specification.Generators.Tests;

public sealed class SpecificationGeneratorTests
{
    private const string ExpectedAttributeSource = """
            // <auto-generated/>
            namespace EricksonLopez.Specification
            {
                /// <summary>
                /// Marks a class for specification source generation.
                /// The generator will emit strongly-typed ordering helpers.
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                public sealed class SpecAttribute : global::System.Attribute
                {
                    /// <summary>Gets the entity type.</summary>
                    public global::System.Type? EntityType { get; }

                    /// <summary>Initializes a new instance of the attribute.</summary>
                    public SpecAttribute(global::System.Type? entityType = null) => EntityType = entityType;
                }
            }
            """;

    private const string ExpectedColumnResolverAttributeSource = """
            // <auto-generated/>
            namespace EricksonLopez.Specification
            {
                /// <summary>
                /// Specifies the naming convention for SQL column names.
                /// </summary>
                public enum NamingConvention
                {
                    /// <summary>Snake case (e.g., total_purchases).</summary>
                    SnakeCase = 0,
                    /// <summary>Pascal case (e.g., TotalPurchases).</summary>
                    PascalCase = 1,
                    /// <summary>Camel case (e.g., totalPurchases).</summary>
                    CamelCase = 2,
                    /// <summary>Exact property name match.</summary>
                    Exact = 3
                }

                /// <summary>
                /// Generates a compile-time zero-reflection IColumnNameResolver implementation.
                /// </summary>
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                public sealed class SpecColumnResolverAttribute : global::System.Attribute
                {
                    /// <summary>Gets the entity type.</summary>
                    public global::System.Type EntityType { get; }

                    /// <summary>Gets or sets the column naming convention.</summary>
                    public NamingConvention Convention { get; set; } = NamingConvention.SnakeCase;

                    /// <summary>Initializes a new instance of the attribute.</summary>
                    public SpecColumnResolverAttribute(global::System.Type entityType) => EntityType = entityType;
                }
            }
            """;

    [Fact]
    public void Descriptor_HasCorrectProperties()
    {
        var descriptor = SpecificationGenerator.RequiresPartialDescriptor;
        descriptor.Id.Should().Be("SPEC100");
        descriptor.DefaultSeverity.Should().Be(DiagnosticSeverity.Error);
        descriptor.Title.ToString().Should().Be("Specification class must be partial");
        descriptor.MessageFormat.ToString().Should().Be("'{0}' is decorated with [Spec] but is not declared as partial. Add the 'partial' keyword.");
        descriptor.Category.Should().Be("Specification");
        descriptor.IsEnabledByDefault.Should().BeTrue();
    }

    [Fact]
    public async Task Generator_AlwaysEmitsSpecAttribute()
    {
        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = "",
        };

        test.ExpectedDiagnostics.Clear();
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_WithPartialClass_EmitsOrderingHelpers()
    {
        var testCode = """
            using EricksonLopez.Specification;
            
            namespace MyDomain;

            [Spec]
            public partial class CustomerSpecifications
            {
            }
            """;

        var expectedCode = """
            // <auto-generated/>
            namespace MyDomain;
            
            partial class CustomerSpecifications
            {
                // Strongly-typed ordering helpers generated by EricksonLopez.Specification.Generators
                // Add properties to your entity class and they will appear here as ordering expressions.
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
        };

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "CustomerSpecifications.g.cs",
            expectedCode));

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_WithGlobalNamespacePartialClass_EmitsCorrectly()
    {
        var testCode = """
            using EricksonLopez.Specification;

            [Spec]
            public partial class GlobalSpecifications
            {
            }
            """;

        var expectedCode = """
            // <auto-generated/>
            
            
            partial class GlobalSpecifications
            {
                // Strongly-typed ordering helpers generated by EricksonLopez.Specification.Generators
                // Add properties to your entity class and they will appear here as ordering expressions.
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
        };

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "GlobalSpecifications.g.cs",
            expectedCode));

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_WithEntityType_EmitsTypedOrderingHelpers()
    {
        var testCode = """
            using EricksonLopez.Specification;

            namespace MyDomain;

            public class Customer
            {
                public int Id { get; set; }
                public string Name { get; set; }
            }

            [Spec(typeof(Customer))]
            public partial class CustomerOrdering
            {
            }
            """;

        var expectedCode = """
            // <auto-generated/>
            namespace MyDomain;

            partial class CustomerOrdering
            {
                public static readonly global::System.Linq.Expressions.Expression<global::System.Func<global::MyDomain.Customer, object?>> OrderById = x => (object?)x.Id;
                public static readonly global::System.Linq.Expressions.Expression<global::System.Func<global::MyDomain.Customer, object?>> OrderByName = x => (object?)x.Name;
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
        };

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "CustomerOrdering.g.cs",
            expectedCode));

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_WithNonPartialClass_EmitsDiagnostic()
    {
        var testCode = """
            using EricksonLopez.Specification;

            namespace MyDomain;

            [Spec]
            public class BadSpecifications
            {
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
        };

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        // Expect SPEC100 error at the class declaration
        test.ExpectedDiagnostics.Add(
            new DiagnosticResult("SPEC100", DiagnosticSeverity.Error)
                .WithSpan(6, 14, 6, 31) // "BadSpecifications"
                .WithArguments("BadSpecifications")
        );

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_WithSpecColumnResolver_EmitsColumnResolverImplementation()
    {
        var testCode = """
            using EricksonLopez.Specification;

            namespace MyDomain;

            public class Customer
            {
                public int Id { get; set; }
                public string Name { get; set; } = "";
                public decimal TotalPurchases { get; set; }
            }

            [SpecColumnResolver(typeof(Customer))]
            public partial class CustomerColumns
            {
            }
            """;

        var expectedCode = """
            // <auto-generated/>
            #nullable enable
            namespace MyDomain;

            partial class CustomerColumns : global::EricksonLopez.Specification.Sql.IColumnNameResolver
            {
                public static readonly CustomerColumns Instance = new();

                public string Resolve(string propertyName) => propertyName switch
                {
                    "Id" => "id",
                    "Name" => "name",
                    "TotalPurchases" => "total_purchases",
                    _ => throw new global::System.ArgumentException($"Unknown property '{propertyName}' for entity 'Customer'.", nameof(propertyName))
                };
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
            CompilerDiagnostics = CompilerDiagnostics.None,
        };

        test.TestState.AdditionalReferences.Add(typeof(EricksonLopez.Specification.Sql.IColumnNameResolver).Assembly);

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "CustomerColumns.g.cs",
            expectedCode));

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_WithSpecColumnResolver_StaticClass_EmitsStaticResolve()
    {
        var testCode = """
            using EricksonLopez.Specification;

            namespace MyDomain;

            public class Customer
            {
                public int Id { get; set; }
                public string Name { get; set; } = "";
            }

            [SpecColumnResolver(typeof(Customer))]
            public static partial class CustomerColumns
            {
            }
            """;

        var expectedCode = """
            // <auto-generated/>
            #nullable enable
            namespace MyDomain;

            partial class CustomerColumns
            {
                public static string Resolve(string propertyName) => propertyName switch
                {
                    "Id" => "id",
                    "Name" => "name",
                    _ => throw new global::System.ArgumentException($"Unknown property '{propertyName}' for entity 'Customer'.", nameof(propertyName))
                };
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
            CompilerDiagnostics = CompilerDiagnostics.None,
        };

        test.TestState.AdditionalReferences.Add(typeof(EricksonLopez.Specification.Sql.IColumnNameResolver).Assembly);

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "CustomerColumns.g.cs",
            expectedCode));

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_WithSpecColumnResolver_PascalCase_EmitsPascalCaseNames()
    {
        var testCode = """
            using EricksonLopez.Specification;

            namespace MyDomain;

            public class Customer
            {
                public int Id { get; set; }
                public decimal TotalPurchases { get; set; }
            }

            [SpecColumnResolver(typeof(Customer), Convention = NamingConvention.PascalCase)]
            public partial class CustomerColumns
            {
            }
            """;

        var expectedCode = """
            // <auto-generated/>
            #nullable enable
            namespace MyDomain;

            partial class CustomerColumns : global::EricksonLopez.Specification.Sql.IColumnNameResolver
            {
                public static readonly CustomerColumns Instance = new();

                public string Resolve(string propertyName) => propertyName switch
                {
                    "Id" => "Id",
                    "TotalPurchases" => "TotalPurchases",
                    _ => throw new global::System.ArgumentException($"Unknown property '{propertyName}' for entity 'Customer'.", nameof(propertyName))
                };
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
            CompilerDiagnostics = CompilerDiagnostics.None,
        };

        test.TestState.AdditionalReferences.Add(typeof(EricksonLopez.Specification.Sql.IColumnNameResolver).Assembly);

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "CustomerColumns.g.cs",
            expectedCode));

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_WithSpecColumnResolver_NonPartialClass_EmitsDiagnostic()
    {
        var testCode = """
            using EricksonLopez.Specification;

            namespace MyDomain;

            public class Customer { public int Id { get; set; } }

            [SpecColumnResolver(typeof(Customer))]
            public class BadColumns
            {
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
            CompilerDiagnostics = CompilerDiagnostics.None,
        };

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        test.ExpectedDiagnostics.Add(
            new DiagnosticResult("SPEC100", DiagnosticSeverity.Error)
                .WithSpan(8, 14, 8, 24)
                .WithArguments("BadColumns"));

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_WithSpecColumnResolver_CamelCase_EmitsCamelCaseNames()
    {
        var testCode = """
            using EricksonLopez.Specification;

            namespace MyDomain;

            public class Customer
            {
                public int Id { get; set; }
                public decimal TotalPurchases { get; set; }
            }

            [SpecColumnResolver(typeof(Customer), Convention = NamingConvention.CamelCase)]
            public partial class CustomerColumns : global::EricksonLopez.Specification.Sql.IColumnNameResolver
            {
            }
            """;

        var expectedCode = """
            // <auto-generated/>
            #nullable enable
            namespace MyDomain;

            partial class CustomerColumns : global::EricksonLopez.Specification.Sql.IColumnNameResolver
            {
                public static readonly CustomerColumns Instance = new();

                public string Resolve(string propertyName) => propertyName switch
                {
                    "Id" => "id",
                    "TotalPurchases" => "totalPurchases",
                    _ => throw new global::System.ArgumentException($"Unknown property '{propertyName}' for entity 'Customer'.", nameof(propertyName))
                };
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
            CompilerDiagnostics = CompilerDiagnostics.None,
        };

        test.TestState.AdditionalReferences.Add(typeof(EricksonLopez.Specification.Sql.IColumnNameResolver).Assembly);

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "CustomerColumns.g.cs",
            expectedCode));

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_WithSpecColumnResolver_Exact_EmitsExactNames()
    {
        var testCode = """
            using EricksonLopez.Specification;

            namespace MyDomain;

            public class Customer
            {
                public int Id { get; set; }
                public decimal TotalPurchases { get; set; }
            }

            [SpecColumnResolver(typeof(Customer), Convention = NamingConvention.Exact)]
            public partial class CustomerColumns : global::EricksonLopez.Specification.Sql.IColumnNameResolver
            {
            }
            """;

        var expectedCode = """
            // <auto-generated/>
            #nullable enable
            namespace MyDomain;

            partial class CustomerColumns : global::EricksonLopez.Specification.Sql.IColumnNameResolver
            {
                public static readonly CustomerColumns Instance = new();

                public string Resolve(string propertyName) => propertyName switch
                {
                    "Id" => "Id",
                    "TotalPurchases" => "TotalPurchases",
                    _ => throw new global::System.ArgumentException($"Unknown property '{propertyName}' for entity 'Customer'.", nameof(propertyName))
                };
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
            CompilerDiagnostics = CompilerDiagnostics.None,
        };

        test.TestState.AdditionalReferences.Add(typeof(EricksonLopez.Specification.Sql.IColumnNameResolver).Assembly);

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "CustomerColumns.g.cs",
            expectedCode));

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_WithSpecColumnResolver_GlobalNamespace_EmitsCorrectly()
    {
        var testCode = """
            using EricksonLopez.Specification;

            public class Customer
            {
                public int Id { get; set; }
            }

            [SpecColumnResolver(typeof(Customer))]
            public partial class GlobalCustomerColumns
            {
            }
            """;

        var expectedCode = """
            // <auto-generated/>
            #nullable enable
            

            partial class GlobalCustomerColumns : global::EricksonLopez.Specification.Sql.IColumnNameResolver
            {
                public static readonly GlobalCustomerColumns Instance = new();

                public string Resolve(string propertyName) => propertyName switch
                {
                    "Id" => "id",
                    _ => throw new global::System.ArgumentException($"Unknown property '{propertyName}' for entity 'Customer'.", nameof(propertyName))
                };
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
            CompilerDiagnostics = CompilerDiagnostics.None,
        };

        test.TestState.AdditionalReferences.Add(typeof(EricksonLopez.Specification.Sql.IColumnNameResolver).Assembly);

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "GlobalCustomerColumns.g.cs",
            expectedCode));

        await test.RunAsync();
    }

    [Fact]
    public void ConvertName_And_ToSnakeCase_WithEdgeCases_TransformsCorrectly()
    {
        var convertMethod = typeof(SpecificationGenerator).GetMethod("ConvertName", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)!;
        var toSnakeCaseMethod = typeof(SpecificationGenerator).GetMethod("ToSnakeCase", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)!;

        // ConvertName conventions:
        convertMethod.Invoke(null, new object[] { "FirstName", 1 }).Should().Be("FirstName"); // Pascal
        convertMethod.Invoke(null, new object[] { "FirstName", 2 }).Should().Be("firstName"); // Camel
        convertMethod.Invoke(null, new object[] { "FirstName", 3 }).Should().Be("FirstName"); // Exact
        convertMethod.Invoke(null, new object[] { "FirstName", 0 }).Should().Be("first_name"); // Snake

        // ToSnakeCase empty and edge cases
        toSnakeCaseMethod.Invoke(null, new object[] { "" }).Should().Be("");
        toSnakeCaseMethod.Invoke(null, new object[] { "A" }).Should().Be("a");
        toSnakeCaseMethod.Invoke(null, new object[] { "already_snake" }).Should().Be("already_snake");
        toSnakeCaseMethod.Invoke(null, new object[] { "already_Snake" }).Should().Be("already_snake");
    }

    [Fact]
    public async Task Generator_WithSpecColumnResolver_IgnoresPrivateAndStaticProperties()
    {
        var testCode = """
            using EricksonLopez.Specification;

            namespace MyDomain;

            public class Customer
            {
                public int Id { get; set; }
                public static string Category { get; set; } = "VIP";
                private string Secret { get; set; } = "hidden";
            }

            [SpecColumnResolver(typeof(Customer))]
            public partial class CustomerColumns
            {
            }
            """;

        var expectedCode = """
            // <auto-generated/>
            #nullable enable
            namespace MyDomain;

            partial class CustomerColumns : global::EricksonLopez.Specification.Sql.IColumnNameResolver
            {
                public static readonly CustomerColumns Instance = new();

                public string Resolve(string propertyName) => propertyName switch
                {
                    "Id" => "id",
                    _ => throw new global::System.ArgumentException($"Unknown property '{propertyName}' for entity 'Customer'.", nameof(propertyName))
                };
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
            CompilerDiagnostics = CompilerDiagnostics.None,
        };

        test.TestState.AdditionalReferences.Add(typeof(EricksonLopez.Specification.Sql.IColumnNameResolver).Assembly);

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "CustomerColumns.g.cs",
            expectedCode));

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_WithSpecAttribute_WithoutExplicitType_InfersFromBaseSpecificationClass()
    {
        var testCode = """
            using EricksonLopez.Specification;

            namespace MyDomain;

            public class Customer
            {
                public int Id { get; set; }
            }

            public abstract class Specification<T> { }

            [Spec]
            public partial class CustomerSpec : Specification<Customer>
            {
            }
            """;

        var expectedCode = """
            // <auto-generated/>
            namespace MyDomain;

            partial class CustomerSpec
            {
                public static readonly global::System.Linq.Expressions.Expression<global::System.Func<global::MyDomain.Customer, object?>> OrderById = x => (object?)x.Id;
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
            CompilerDiagnostics = CompilerDiagnostics.None,
        };

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "CustomerSpec.g.cs",
            expectedCode));

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_WithSpecColumnResolver_WithCustomNamingConvention_EmitsCorrectConvention()
    {
        var testCode = """
            using EricksonLopez.Specification;

            namespace MyDomain;

            public class Customer
            {
                public int Id { get; set; }
                public string FirstName { get; set; } = string.Empty;
            }

            [SpecColumnResolver(typeof(Customer), Convention = NamingConvention.PascalCase)]
            public partial class CustomerColumns
            {
            }
            """;

        var expectedCode = """
            // <auto-generated/>
            #nullable enable
            namespace MyDomain;

            partial class CustomerColumns : global::EricksonLopez.Specification.Sql.IColumnNameResolver
            {
                public static readonly CustomerColumns Instance = new();

                public string Resolve(string propertyName) => propertyName switch
                {
                    "Id" => "Id",
                    "FirstName" => "FirstName",
                    _ => throw new global::System.ArgumentException($"Unknown property '{propertyName}' for entity 'Customer'.", nameof(propertyName))
                };
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
            CompilerDiagnostics = CompilerDiagnostics.None,
        };

        test.TestState.AdditionalReferences.Add(typeof(EricksonLopez.Specification.Sql.IColumnNameResolver).Assembly);

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "CustomerColumns.g.cs",
            expectedCode));

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_WithSpecColumnResolver_WithNullEntityType_DoesNotGenerateCode()
    {
        var testCode = """
            using EricksonLopez.Specification;

            namespace MyDomain;

            [SpecColumnResolver(null!)]
            public partial class CustomerColumns
            {
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
            CompilerDiagnostics = CompilerDiagnostics.None,
        };

        test.TestState.AdditionalReferences.Add(typeof(EricksonLopez.Specification.Sql.IColumnNameResolver).Assembly);

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        // No CustomerColumns.g.cs generated because entityType is null

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_WithSpec_IgnoresPrivateAndStaticProperties()
    {
        var testCode = """
            using EricksonLopez.Specification;

            namespace MyDomain;

            public class Customer
            {
                public int Id { get; set; }
                public static string Category { get; set; } = "VIP";
                private string Secret { get; set; } = "hidden";
            }

            [Spec(typeof(Customer))]
            public partial class CustomerSpec
            {
            }
            """;

        var expectedCode = """
            // <auto-generated/>
            namespace MyDomain;

            partial class CustomerSpec
            {
                public static readonly global::System.Linq.Expressions.Expression<global::System.Func<global::MyDomain.Customer, object?>> OrderById = x => (object?)x.Id;
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
            CompilerDiagnostics = CompilerDiagnostics.None,
        };

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "CustomerSpec.g.cs",
            expectedCode));

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_WithSpec_WithNonSpecificationGenericBase_EmitsDefaultComment()
    {
        var testCode = """
            using EricksonLopez.Specification;

            namespace MyDomain;

            public class Customer
            {
                public int Id { get; set; }
            }

            public abstract class OtherBase<T> { }

            [Spec]
            public partial class CustomerSpec : OtherBase<Customer>
            {
            }
            """;

        var expectedCode = """
            // <auto-generated/>
            namespace MyDomain;

            partial class CustomerSpec
            {
                // Strongly-typed ordering helpers generated by EricksonLopez.Specification.Generators
                // Add properties to your entity class and they will appear here as ordering expressions.
            }
            """;

        var test = new CSharpSourceGeneratorTest<SpecificationGenerator, DefaultVerifier>
        {
            TestCode = testCode,
            CompilerDiagnostics = CompilerDiagnostics.None,
        };

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecAttribute.g.cs",
            ExpectedAttributeSource));
        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "SpecColumnResolverAttribute.g.cs",
            ExpectedColumnResolverAttributeSource));

        test.TestState.GeneratedSources.Add((
            typeof(SpecificationGenerator),
            "CustomerSpec.g.cs",
            expectedCode));

        await test.RunAsync();
    }
}






